import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { SkillAnalysis } from "../services/gemini";

export function generatePDF(analysis: SkillAnalysis, targetRole: string) {
  const doc = new jsPDF();
  const primaryColor: [number, number, number] = [249, 115, 22]; // Tailwind orange-500

  // Title
  doc.setFontSize(22);
  doc.setTextColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.text("SkillSense AI Analysis", 14, 20);

  // Subtitle
  doc.setFontSize(14);
  doc.setTextColor(100, 100, 100);
  doc.text(`Target Role: ${targetRole}`, 14, 30);
  doc.text(`Skill Match: ${analysis.matchPercentage}%`, 14, 37);

  // Line
  doc.setDrawColor(200, 200, 200);
  doc.line(14, 42, 196, 42);

  // Current Skills
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.setFont("helvetica", "bold");
  doc.text("Current Skills:", 14, 52);
  doc.setFont("helvetica", "normal");
  const currentSkillsText = analysis.currentSkills.join(", ");
  const splitCurrentSkills = doc.splitTextToSize(currentSkillsText, 180);
  doc.text(splitCurrentSkills, 14, 59);

  let currentY = 59 + (splitCurrentSkills.length * 7);

  // Missing Skills
  doc.setFont("helvetica", "bold");
  doc.text("Detected Gaps (Missing Skills):", 14, currentY + 5);
  doc.setFont("helvetica", "normal");
  const missingSkillsText = analysis.missingSkills.join(", ");
  const splitMissingSkills = doc.splitTextToSize(missingSkillsText, 180);
  doc.text(splitMissingSkills, 14, currentY + 12);

  currentY = currentY + 12 + (splitMissingSkills.length * 7);

  // Gap Analysis
  doc.setFont("helvetica", "bold");
  doc.text("Agent Reasoning:", 14, currentY + 5);
  doc.setFont("helvetica", "normal");
  const splitGapAnalysis = doc.splitTextToSize(analysis.gapAnalysis, 180);
  doc.text(splitGapAnalysis, 14, currentY + 12);

  currentY = currentY + 12 + (splitGapAnalysis.length * 7);

  // Roadmap Table
  doc.setFont("helvetica", "bold");
  doc.text("4-Week Learning Roadmap:", 14, currentY + 10);

  const tableData = analysis.roadmap.map((step) => [
    step.week,
    step.topic,
    step.description,
    step.resources.map((r) => r.title).join("\n")
  ]);

  autoTable(doc, {
    startY: currentY + 15,
    head: [["Week", "Topic", "Description", "Resources"]],
    body: tableData,
    headStyles: { fillColor: primaryColor },
    styles: { fontSize: 10, cellPadding: 5 },
    columnStyles: {
      0: { cellWidth: 20 },
      1: { cellWidth: 40 },
      2: { cellWidth: 60 },
      3: { cellWidth: 60 }
    }
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Generated by SkillSense AI - Page ${i} of ${pageCount}`,
      105,
      doc.internal.pageSize.getHeight() - 10,
      { align: "center" }
    );
  }

  doc.save(`SkillSense_AI_Roadmap_${targetRole.replace(/\s+/g, "_")}.pdf`);
}
